# Pre-commit hooks configuration

default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
      - id: end-of-file-fixer
        name: fix end of files
      - id: check-yaml
        name: check yaml syntax
        args: [--unsafe]
      - id: check-json
        name: check json syntax
      - id: check-toml
        name: check toml syntax
      - id: check-added-large-files
        name: check for large files
        args: [--maxkb=500]
      - id: check-merge-conflict
        name: check for merge conflicts
      - id: check-case-conflict
        name: check for case conflicts
      # - id: detect-private-key
      #   name: detect private keys
      - id: mixed-line-ending
        name: fix mixed line endings
        args: [--fix=lf]
      # - id: check-executables-have-shebangs
      #   name: check executables have shebangs
      # - id: check-shebang-scripts-are-executable
      #   name: check shebang scripts are executable
      
# Configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: monthly
